# fly.toml app configuration file for noot-nootio backend
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'noot-nootio'
primary_region = 'fra' # Frankfurt, Germany (Chosen for Kazakhstan proximity)

# Explicitly define the build settings
[build]
  # Specify the Dockerfile to use, relative to the project root
  dockerfile = "backend/Dockerfile"

# No explicit build section needed, Dockerfile will be used

# No http_service section needed if only using TCP services for WS
# [[http_service]] # Keep commented unless specifically needed for non-WS traffic
#   internal_port = 8080
#   force_https = true
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0
#   processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256 # Backend might need less memory than frontend initially

[[services]]
  protocol = "tcp"
  internal_port = 8080 # Port the backend server listens on
  processes = ["app"] # Process group named "app" by default

  [[services.ports]]
    port = 80 # For HTTP -> WS upgrade
    handlers = ["http"]
    force_https = true # Redirect HTTP to HTTPS

  [[services.ports]]
    port = 443 # For HTTPS -> WSS upgrade
    handlers = ["tls", "http"] # TLS termination + HTTP handling

  # TCP check ensures the port is open
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  # HTTP check verifies the app is responding to HTTP requests
  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/" # Path for the health check endpoint in server.js
    protocol = "http" # Check against internal HTTP port
    # tls_skip_verify = false # Keep verification unless using self-signed certs internally
    # [services.http_checks.headers]
    #   Host = "your.backend.hostname" # Usually not needed unless app requires specific Host header

# [build]
#  builder = 'paketobuildpacks/builder:base' 